CREATE TABLE TODOS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY
    user_id BIGINT NOT NULL
    title VARCHAR(255) NOT NULL
    todo  VARCHAR(255) NOT NULL
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE USERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY
    username VARCHAR(255) NOT NULL
    email  VARCHAR(255) NOT NULL
    password VARCHAR(255) NOT NULL
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);